# Generated by Django 4.0.6 on 2022-07-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlbApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='plato',
            name='descripcion',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_cliente_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='rlbApp.cliente'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='dia_semana',
            field=models.CharField(max_length=10, verbose_name='Dia semana'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
