# Generated by Django 4.0.6 on 2022-07-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlbApp', '0002_remove_cliente_nombre_remove_cliente_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha reserva')),
                ('cant_personas', models.IntegerField(default=0, verbose_name='Cantidad personas')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('id_cliente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='rlbApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_mesa', models.CharField(max_length=100, unique=True, verbose_name='Numero mesa')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('aforo', models.IntegerField(verbose_name='Aforo')),
                ('id_cliente_fk', models.ManyToManyField(related_name='mesa', to='rlbApp.cliente')),
            ],
        ),
    ]
