# Generated by Django 4.0.6 on 2022-07-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlbApp', '0003_reserva_mesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='id_cliente_fk',
            new_name='cliente',
        ),
    ]
