# Generated by Django 4.0.6 on 2022-08-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlbApp', '0005_remove_user_id_cliente_fk_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='aforo',
        ),
        migrations.AddField(
            model_name='mesa',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
